"""Single source of truth for model IDs across MARS.

When a new frontier model launches, update the IDs in THIS file only:
  - FRONTIER_MODELS    - the debaters/orchestrator defaults the wizard offers
  - VALIDATION_MODELS  - the cheap models used for 1-token key-validation pings

Everything else derives from here:
  - mars/setup_wizard.py imports FRONTIER_MODELS, VALIDATION_MODELS, SUPPORTED_PROVIDERS
  - config.example.yaml is regenerated by running:  python -m mars.registry

config.yaml is the operator's own runtime file (written by the wizard or hand-edited)
and is intentionally NOT regenerated here - it reflects the providers/roles you chose.
"""

from pathlib import Path

SUPPORTED_PROVIDERS = ["anthropic", "openai", "gemini"]

# provider -> (model_id, display label shown in the wizard's role menus)
FRONTIER_MODELS = {
    "anthropic": ("claude-opus-4-8",                 "Claude Opus 4.8          - frontier, strongest reasoning"),
    "openai":    ("gpt-5.5",                          "GPT-5.5                  - OpenAI frontier"),
    "gemini":    ("gemini/gemini-3.1-pro-preview",    "Gemini 3.1 Pro Preview   - Google frontier"),
}

# provider -> cheapest model, used for the 1-token key-validation ping (near-zero cost)
VALIDATION_MODELS = {
    "anthropic": "anthropic/claude-haiku-4-5-20251001",
    "openai":    "openai/gpt-4o-mini",
    "gemini":    "gemini/gemini-2.0-flash-lite",
}


def render_example_config() -> str:
    """Build config.example.yaml from the model registry, so the example
    never drifts from the IDs the wizard actually uses."""
    from mars.config import MAX_ROUNDS

    anthropic = FRONTIER_MODELS["anthropic"][0]
    openai = FRONTIER_MODELS["openai"][0]
    gemini = FRONTIER_MODELS["gemini"][0]
    return f"""\
# MARS configuration.
#
# Two frontier models refine a vague idea into a watertight one: the primary builds,
# the challenger pressure-tests, the primary defends/revises, the orchestrator delivers
# the hardened result. Configure one model per provider, then map roles to them.
#
# RULES (enforced in code):
#   - At least 2 providers must be configured.
#   - Every role must map to a configured provider.
#   - primary and adversarial MUST be different providers - the two debaters need to be
#     genuine peers from different families, or you get correlated blind spots.
#   - orchestrator may share a provider with primary.
#   - rounds: 1 to {MAX_ROUNDS}. The max of {MAX_ROUNDS} is a hard cap in code; config cannot exceed it.
#
# Put the two STRONGEST models on primary and adversarial - they are peers debating, so a
# mismatch (a weak model vs a frontier one) collapses the refinement. The orchestrator
# writes your deliverable, so keep it strong too; do not cheap out there.
#
# Model IDs here are generated from mars/registry.py - edit them there, then regenerate
# with `python -m mars.registry`.

providers:
  anthropic:
    model: {anthropic}              # frontier flagship
  openai:
    model: {openai}                      # frontier flagship
  gemini:
    model: {gemini}  # frontier flagship (optional third)

roles:
  primary: openai                 # builds the idea, then defends/revises each round
  adversarial: anthropic          # peer challenger - must be a frontier model, this is load-bearing
  orchestrator: openai            # synthesizes the hardened idea (your deliverable); keep it strong

rounds:
  default: 2                      # used when --rounds is not passed
  max: {MAX_ROUNDS}                          # hard cap; code refuses anything above {MAX_ROUNDS}
"""


if __name__ == "__main__":
    out = Path(__file__).resolve().parent.parent / "config.example.yaml"
    out.write_text(render_example_config())
    print(f"Wrote {out}")
